# https://docs.docker.com/registry/deploying/
consul1:
  restart: always
  image: makensi/microservices:example-consul
  container_name: consul1
  hostname: consul1
  ports:
    - 8200:80
    - 8300:8300
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400
    - 8500:8500
    - 8600:8600/udp
consul2:
  restart: always
  image: makensi/microservices:example-consul
  container_name: consul2
  hostname: consul2
  links:
    - consul1:consul1
consul3:
  restart: always
  image: makensi/microservices:example-consul
  container_name: consul3
  hostname: consul3
  links:
    - consul1:consul1
nginx-proxy:
  restart: always
  image: makensi/microservices:example-nginx-proxy
  container_name: nginx-proxy
  hostname: nginx-proxy
  links:
    - consul1:consul1
    - consul2:consul2
    - consul3:consul3
  ports:
    - 8100:80
nginx1:
  restart: always
  image: makensi/microservices:example-nginx
  container_name: nginx1
  hostname: nginx1
  links:
    - consul1:consul1
    - consul2:consul2
    - consul3:consul3
nginx2:
  restart: always
  image: makensi/microservices:example-nginx
  container_name: nginx2
  hostname: nginx2
  links:
    - consul1:consul1
    - consul2:consul2
    - consul3:consul3
nginx3:
  restart: always
  image: makensi/microservices:example-nginx
  container_name: nginx3
  hostname: nginx3
  links:
    - consul1:consul1
    - consul2:consul2
    - consul3:consul3